### ISSUE TITLE
Manual curation of used KEGG database

### ISSUE THREAD

**Issue by Juleny** [OSS-Lab/MetQy#4]
Dear Andreas, 
I would like to use your tool to analyse the metabolic potential of MAGs. I have tested it already and found out that a few modules are missing. Unfortunately, I do not have access to the KEGG ftp but I wonder if I could make manual modifications (adding modules) to the existing KEGG database file that is used in the package. 
Do you think that is possible? 

Many thanks
Julia

**Comment by asmvernon** [comment]
Hi Julia,
Yes, that should be possible :)

I think you should be able to pull the data from
https://github.com/OSS-Lab/MetQy/blob/master/MetQy_1.1.0/R/sysdata.rda,
modify it to add the new modules, and pass it using the
"use_module_reference_table" argument.

Hope that works!

Thanks,
Andrea
------------
Andrea Martinez Vernon, PhD
LinkedIn: https://www.linkedin.com/in/andrea-martinez-vernon/

**Comment by Juleny** [comment]
Thank you Andrea, that worked very well :).

Julia
